### ISSUE TITLE
libvirt-actuator is broken

### ISSUE THREAD

**Issue by jhou1** [openshift/cluster-api-provider-libvirt#77]
Hi, I was trying to follow https://github.com/openshift/cluster-api-provider-libvirt/tree/master/cmd/libvirt-actuator to create libvirt instance. I failed at step `./bin/libvirt-actuator create -m examples/machine.yaml -c examples/cluster.yaml`

```
#  ./bin/libvirt-actuator create -m examples/machine.yaml -c examples/cluster.yaml
ERROR: logging before flag.Parse: I1029 05:21:21.536376   29201 actuator.go:86] Creating machine "worker-example" for cluster "tb-asg-35".
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xee6683]

goroutine 1 [running]:
github.com/openshift/cluster-api-provider-libvirt/pkg/cloud/libvirt/actuators/machine.ProviderConfigMachine(0x0, 0x0, 0xc00031c688, 0xc000000000, 0x12451f5, 0x23)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/pkg/cloud/libvirt/actuators/machine/actuator.go:236 +0x53
github.com/openshift/cluster-api-provider-libvirt/pkg/cloud/libvirt/actuators/machine.clientForMachine(0x0, 0x0, 0xc00031c580, 0x2, 0x2, 0xc000307d80)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/pkg/cloud/libvirt/actuators/machine/actuator.go:352 +0x4b
github.com/openshift/cluster-api-provider-libvirt/pkg/cloud/libvirt/actuators/machine.(*Actuator).Create(0xc000307d80, 0xc0002df040, 0xc00031c580, 0x0, 0x0)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/pkg/cloud/libvirt/actuators/machine/actuator.go:89 +0x135
main.init.0.func1(0xc0002c5400, 0xc000307a80, 0x0, 0x4, 0x0, 0x0)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/cmd/libvirt-actuator/main.go:61 +0x224
github.com/openshift/cluster-api-provider-libvirt/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002c5400, 0xc000307a40, 0x4, 0x4, 0xc0002c5400, 0xc000307a40)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/openshift/cluster-api-provider-libvirt/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1fece60, 0xc0002e06e0, 0x136cb60, 0xc00000e018)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/openshift/cluster-api-provider-libvirt/vendor/github.com/spf13/cobra.(*Command).Execute(0x1fece60, 0xc00000e018, 0xc0000cff88)
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/root/go/src/github.com/openshift/cluster-api-provider-libvirt/cmd/libvirt-actuator/main.go:143 +0x5c
```

## System Info

```
[root@dhcp-66-145-109 cluster-api-provider-libvirt]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@dhcp-66-145-109 cluster-api-provider-libvirt]# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false


libvirt-libs-3.9.0-14.el7_5.8.x86_64
libvirt-devel-3.9.0-14.el7_5.8.x86_64
libvirt-daemon-3.9.0-14.el7_5.8.x86_64
libvirt-3.9.0-14.el7_5.8.x86_64

go version go1.11.1 linux/amd64
```

`bin/libvirt-actuator` was built from on the `crd` branch. Please let me know what more I should provide here. 
Thank you.

**Comment by cfergeau** [comment]
The `libvirt-actuator` binary has been removed in commit ff2852bcd3c
